version: '3.8'

services:
  visionguard-api:
    build: .
    runtime: runc
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./server/uploads:/app/server/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000
